### PR TITLE
Fix plugin-js object keys, sort tokens

### LINKED ISSUE #91: Modes can't begin with numbers
I created a "fontSize" `dimension` with a variety of modes, but I was surprised to find out that mode names can't be prefixed with numbers

Screenshot 2023-08-28 at 5 15 08 PM

Is this expected? Or is this a bug?

### PR DESCRIPTION
**Pull request by drwpow**
## Changes

Fixes #91. JS-valid keys weren’t being properly sniffed out, which led to invalid code generation.

Also sorts token keys so they will appear in a more predictable order.

## How to Review

- Tests should pass

### CODE REVIEW

File: packages/plugin-js/test/border/want.js [hunk 1]
```diff
@@ -14,14 +14,14 @@ export const tokens = {
 
 export const meta = {
   border: {
-    '_original': {
-      '$type': 'border',
```
Comment (drwpow) [inline packages/plugin-js/test/border/want.js:18]: This is now cleaner—these didn’t need quotes

File: packages/plugin-js/test/nested/want.d.ts [hunk 2]
```diff
@@ -13,57 +13,57 @@ export declare const tokens: {
...
-      20: ParsedColorToken;
-      30: ParsedColorToken;
-      40: ParsedColorToken;
-      50: ParsedColorToken;
-      60: ParsedColorToken;
-      70: ParsedColorToken;
-      80: ParsedColorToken;
-      90: ParsedColorToken;
-      100: ParsedColorToken;
+      '10': ParsedColorToken;
```
Comment (drwpow) [inline packages/plugin-js/test/nested/want.d.ts:40]: Now numbers get quoted. This shouldn’t be a breaking change; just errs on the side of safety (esp. with zero-padded numbers like `00`)
